---
name: Module-Info-File
version: 0.11
author:
  - 'Jonas B. Nielsen, <jonasbn@cpan.org>'
abstract: retrieves module information from a file or script
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Data::Dumper: 0
  File::Spec: 0
  Module::Info: 0.20
  Test::Harness: 0
  Test::More: 0
  UNIVERSAL: 0
provides:
  Module::Info::File:
    file: lib/Module/Info/File.pm
    version: 0.11
no_index:
  directory:
    - drafts
    - t
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
